name: Lint

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Use pnpm '7'
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install Dependencies with PNPM
        run: pnpm install

      - name: Lint with ESLint
        run: npm run lint
